window.CONCEPTS = [
  {
    id: '01-quiet-rail',
    n: '01',
    name: 'Quiet Rail',
    zh: '底部细条',
    form: '横向 · 左下',
    tier: '完整摘要',
    size: '580 × 84',
    ref: 'ngetrek',
    recommended: false,
    description: '把目标、习惯和下一件事压成一条。用宽度换高度，桌面中心完整留白。',
    tradeoff: '信息完整，但横向较长；更适合 14 英寸以上桌面。',
    implementation: '三列 CSS Grid，固定左下位置，保留 Dock 安全距离。',
    content: `<div class="widget glass rail"><div><div class="eyebrow">Current focus</div><div class="name">Ship the next chapter</div><div class="bar"><span></span></div></div><div><div class="eyebrow">Habits</div><div class="pair"><b>2/3</b><span>this week</span></div></div><div><div class="eyebrow">Next · Oct 12</div><div class="pair"><b>12</b><span>days to Philly</span></div></div></div>`,
  },
  {
    id: '02-margin-notes',
    n: '02',
    name: 'Margin Notes',
    zh: '边缘笔记',
    form: '文字 · 左上',
    tier: '轻摘要',
    size: '242 × 276',
    ref: 'pixel',
    description: '像写在壁纸边缘的几行笔记。没有大块底色，用排版分层取代卡片分组。',
    tradeoff: '留白感强，但复杂壁纸需要更强的文字对比度。',
    implementation: '透明背景、文字阴影与短行宽；明暗壁纸使用不同文字色。',
    content: `<div class="widget margin"><div class="date">Wednesday, September 30</div><h1>A little<br>momentum.</h1><div class="note"><b>Ship the next chapter</b><span class="tiny-line">One focused block today.</span></div><div class="note"><b>Keep the rhythm</b><span class="tiny-line">Deep work ✓ &nbsp; Gym 2/3</span></div><div class="date-footer">Philly in 12 days ↗</div></div>`,
  },
  {
    id: '03-focus-tile',
    n: '03',
    name: 'Focus Tile',
    zh: '专注小卡',
    form: '小卡 · 左下',
    tier: '完整摘要',
    size: '280 × 224',
    ref: 'chronolog',
    recommended: true,
    description: '一个目标做主角，习惯和倒计时只占卡片底部。信息完整，但没有不断向下增长的列表。',
    tradeoff: '一次只显示一个目标、一组习惯摘要和最近倒计时。',
    implementation: '固定尺寸卡片，严格限制条目数；动态内容来自统一的数据模型。',
    content: `<div class="widget glass tile"><header class="tile-heading"><span class="eyebrow">One good thing</span><span class="seed">↗</span></header><h1>Ship the<br>next chapter.</h1><div class="progress-label"><span>Current goal</span><span>58%</span></div><div class="bar"><span></span></div><footer><div><b>Keep the rhythm</b><small>Deep work ✓ &nbsp; Gym 2/3</small></div><div class="count"><b>12 days</b><small>to Philly</small></div></footer></div>`,
  },
  {
    id: '04-horizon-strip',
    n: '04',
    name: 'Horizon Strip',
    zh: '顶部窄带',
    form: '横向 · 顶部',
    tier: '完整摘要',
    size: '740 × 54',
    ref: 'ngetrek',
    description: '放在菜单栏下方的一行仪表。目标进度、习惯和倒计时各留一个短标签。',
    tradeoff: '高度很低，但顶部窗口容易覆盖它；它是桌面层，不是系统菜单栏插件。',
    implementation: '绝对定位在菜单栏下方，用 Flex 排列短标签；不占用系统菜单栏。',
    content: `<div class="widget glass strip"><span class="mark">◌</span><strong>Ship the next chapter</strong><div class="bar strip-progress"><span></span></div><small>58%</small><span class="divider"></span><span>Deep work <span class="accent">✓</span></span><span class="divider"></span><span>Gym <span class="accent">2/3</span></span><span class="spacer"></span><span class="accent">Philly · 12d</span></div>`,
  },
  {
    id: '05-twin-islands',
    n: '05',
    name: 'Twin Islands',
    zh: '双角小岛',
    form: '分散 · 两侧',
    tier: '轻摘要',
    size: '248 × 156 + 212 × 156',
    ref: 'apple',
    description: '目标和倒计时分别停在两个角落。降低每一块的视觉重量，让桌面中间保留完整工作区。',
    tradeoff: '视线需要横跨桌面；左右角都已有图标时不适合。',
    implementation: '同一个 widget 渲染两块区域；容器保持点击穿透。',
    content: `<div class="widget glass island-goal"><div class="eyebrow">A little progress</div><h1>Ship the<br>next chapter.</h1><div class="bar"><span></span></div><div class="under"><span>58% of the way</span><span>↗</span></div></div><div class="widget glass island-date"><div class="eyebrow">On the horizon</div><div class="date-line"><b>12</b><span>days</span></div><div class="dest">Hello, Philadelphia.</div><div class="travel-date">Monday · October 12</div></div>`,
  },
  {
    id: '06-habit-orbit',
    n: '06',
    name: 'Habit Orbit',
    zh: '习惯圆环',
    form: '图形 · 左上',
    tier: '习惯优先',
    size: '244 × 244',
    ref: 'apple',
    description: '用三个小圆环表达今天的习惯状态。减少文字，把“有没有保持节奏”变成一眼可见的信号。',
    tradeoff: '习惯最清晰，目标细节被省略；圆环仍需要简短图例。',
    implementation: 'CSS conic-gradient 圆环，按日与周分别计算；不需要持续动画。',
    content: `<div class="widget glass orbit"><header><span class="eyebrow">Keep the rhythm</span><span class="tag">Today</span></header><div class="rings"><div class="ring r1"></div><div class="ring r2"></div><div class="ring r3"></div><div class="ring-center">1 / 3</div></div><div class="legend"><div>Deep work<b class="accent">Done</b></div><div>Gym<b>2/3 week</b></div><div>Mobility<b class="muted">Not yet</b></div></div><footer>Next up · Philly in 12 days</footer></div>`,
  },
  {
    id: '07-agenda-slip',
    n: '07',
    name: 'Agenda Slip',
    zh: '行程纸条',
    form: '窄列 · 右上',
    tier: '时间优先',
    size: '260 × 312',
    ref: 'chronolog',
    description: '只留一个紧凑的时间清单。近期行动和里程碑按时间排列，避免三个大区块堆叠。',
    tradeoff: '十个方向里纵向占位最大；更适合右侧留有空位的人。',
    implementation: '三条上限的紧凑列表，右侧预留桌面图标列；过期事项不留在 Next up。',
    content: `<div class="widget glass agenda"><div class="eyebrow">A few things ahead</div><h1>Coming up.</h1><div class="event"><div class="when">TOD<br>AY</div><div><b>One focused block</b><small>Ship the next chapter</small></div></div><div class="event"><div class="when">OCT<br>12</div><div><b>Philadelphia</b><small>12 days to go · Travel</small></div></div><div class="event"><div class="when">DEC<br>31</div><div><b>A new work chapter</b><small>92 days to go · Work</small></div></div><footer><span>Deep work ✓</span><span>Gym 2/3 week</span></footer></div>`,
  },
  {
    id: '08-status-chips',
    n: '08',
    name: 'Status Chips',
    zh: '轻量胶囊',
    form: '胶囊 · 左下',
    tier: '轻摘要',
    size: '230 / 150 / 160 × 46',
    ref: 'ngetrek',
    recommended: true,
    description: '三个彼此独立的小胶囊，像轻量状态标记。几乎不改变壁纸，只给出必要的数字。',
    tradeoff: '长标题必须缩短；适合看状态，不适合读详细内容。',
    implementation: '固定长度的三块胶囊，省略长文本；保持静态位置和点击穿透。',
    content: `<div class="widget glass chip goal-chip"><i>↗</i><b>Next chapter</b><small>58%</small></div><div class="widget glass chip habit-chip"><i>✓</i><b>Gym</b><small>2/3 week</small></div><div class="widget glass chip date-chip"><i>◷</i><b>Philly</b><small>12 days</small></div>`,
  },
  {
    id: '09-mono-console',
    n: '09',
    name: 'Mono Console',
    zh: '文字控制台',
    form: '小块 · 左上',
    tier: '完整摘要',
    size: '292 × 196',
    ref: 'pixel',
    description: '用等宽文字和微型进度条做成一个小状态文件。清晰、安静，适合代码工作者的桌面。',
    tradeoff: '数字密度较高，氛围偏技术；可读性依赖合适的字号。',
    implementation: '系统等宽字体和普通 CSS，无终端进程或高频刷新。',
    content: `<div class="widget glass console"><header><span>MOMENTUM / 09.30</span><span class="led">● SAMPLE</span></header><div class="console-title">Ship the next chapter</div><div class="ascii">███████████░░░░░░░░░ &nbsp;58%</div><div class="console-line"><span class="muted">deep_work</span><span class="accent">complete</span></div><div class="console-line"><span class="muted">gym / week</span><span>02 of 03</span></div><div class="status"><span>next → philly</span><span>12 days</span></div></div>`,
  },
  {
    id: '10-one-thing',
    n: '10',
    name: 'One Thing',
    zh: '只留一件事',
    form: '文字 · 左下',
    tier: '单一信号',
    size: '356 × 104',
    ref: 'pixel',
    recommended: true,
    description: '只显示此刻最值得记住的一件事。把 Dashboard 从信息集合重新定义为轻声提醒。',
    tradeoff: '最不占桌面，也牺牲了习惯和倒计时的同时可见性。',
    implementation: '从模型选一个主目标，固定短文本；无需悬停、展开或自动轮播。',
    content: `<div class="widget one-thing"><div class="super">TODAY, ONE GOOD THING</div><h1>Ship the next chapter.</h1><div class="closing"><span>One focused block is enough.</span><div class="bar"><span></span></div><span>58%</span></div></div>`,
  },
];
